apiVersion: v1
kind: Namespace

metadata:
  name: education-persistent-academy-dev

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: persistent-academy
  namespace: education-persistent-academy-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: persistent-academy

  template:
    metadata:
      labels:
        app: persistent-academy

    spec:
      containers:

        - name: persistent-academy

          image: knnrsolomon/education-os:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:
            - name: TENANT_NAME
              value: "persistent-academy"

            - name: TENANT_OS
              value: "education"

            - name: TENANT_ENV
              value: "dev"

---

apiVersion: v1
kind: Service

metadata:
  name: persistent-academy
  namespace: education-persistent-academy-dev

spec:
  selector:
    app: persistent-academy

  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: persistent-academy
  namespace: education-persistent-academy-dev

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: traefik

  rules:

    - host: persistent-academy.education.asmglobal.cloud

      http:
        paths:

          - path: /
            pathType: Prefix

            backend:
              service:
                name: persistent-academy
                port:
                  number: 80

  tls:
    - hosts:
        - persistent-academy.education.asmglobal.cloud

      secretName: persistent-academy-education-tls
