apiVersion: v1
kind: Namespace

metadata:
  name: education-kingdombridge-academy-dev

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: kingdombridge-academy
  namespace: education-kingdombridge-academy-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kingdombridge-academy

  template:
    metadata:
      labels:
        app: kingdombridge-academy

    spec:
      containers:

        - name: kingdombridge-academy

          image: knnrsolomon/education-os:release

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:
            - name: TENANT_NAME
              value: "kingdombridge-academy"

            - name: TENANT_OS
              value: "education"

            - name: TENANT_ENV
              value: "dev"

---

apiVersion: v1
kind: Service

metadata:
  name: kingdombridge-academy
  namespace: education-kingdombridge-academy-dev

spec:
  selector:
    app: kingdombridge-academy

  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: kingdombridge-academy
  namespace: education-kingdombridge-academy-dev

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: traefik

  rules:

    - host: kingdombridge-academy.education.asmglobal.cloud

      http:
        paths:

          - path: /
            pathType: Prefix

            backend:
              service:
                name: kingdombridge-academy
                port:
                  number: 80

  tls:
    - hosts:
        - kingdombridge-academy.education.asmglobal.cloud

      secretName: kingdombridge-academy-education-tls
