---
extends: default

rules:
  line-length: disable
  truthy: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

ignore: |
  apps/**
  infra/**
  root/**
  **/charts/**
  **/crds/**
  **/templates/**
  **/values.yaml
