extends: default

rules:
  line-length: disable
  truthy: disable

ignore: |
  infra/argocd/base/*
  infra/monitoring/base/crds/*
  infra/monitoring/base/charts/*
  infra/monitoring/base/kube-prometheus-stack/*
  infra/monitoring/base/loki-stack/*
  **/charts/*
  **/crds/*
  **/templates/*
  **/*.tpl
  **/*.gotmpl
  **/argocd-install.yaml

