---
extends: default

rules:
  line-length: disable
  truthy: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

ignore: |
  # Broad ignore rules
  apps/**
  infra/**
  root/**
  **/charts/**
  **/crds/**
  **/templates/**

  # Additional CI ignore patterns
  infra/argocd/base/*
  infra/monitoring/base/crds/*
  infra/monitoring/base/charts/*
  infra/monitoring/base/kube-prometheus-stack/*
  infra/monitoring/base/loki-stack/*
  **/*.tpl
  **/*.gotmpl
  **/argocd-install.yaml

  # Helm values files
  **/values.yaml
