---
extends: default

rules:
  line-length: disable
  truthy: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

ignore: |
  # Broad ignore rules (your branch)
  apps/**
  infra/**
  root/**
  **/charts/**
  **/crds/**
  **/templates/**

  # Additional specific ignores (CI branch)
  infra/argocd/base/*
  infra/monitoring/base/crds/*
  infra/monitoring/base/charts/*
  infra/monitoring/base/kube-prometheus-stack/*

  # Common Helm patterns
  **/values.yaml

