extends: default

rules:
  line-length: disable
  truthy: disable
  empty-lines:
    max: 0

ignore: |
  infra/argocd/base/*
  infra/monitoring/base/crds/*
  infra/monitoring/base/charts/*
  infra/monitoring/base/kube-prometheus-stack/*
  **/charts/*
  **/crds/*
  **/templates/*
  **/values.yaml
