apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asm-business-os-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rgi-Asm-Global/asmglobal-platform-os.git
    targetRevision: development
    path: apps/asm-business-os/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: asm-business-system-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
