apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
        app.kubernetes.io/part-of: argocd
    spec:
      containers:
      - name: argocd-repo-server
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
